apiVersion: apps/v1
kind: Deployment
metadata:
  name: spa-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spa
  template:
    metadata:
      labels:
        app: spa
    spec:
      containers:
      - name: spa
        image: tamaramandziuk/nginx_simple_spa:latest
        ports:
          - containerPort: 80